# Generated by Django 5.1.2 on 2025-03-23 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('agent', 'Agent'), ('information', 'Information Officer'), ('cashier', 'Cashier')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +63 XXX-XXX-XXXX', regex='^\\+63 \\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
