# Generated by Django 5.1.2 on 2024-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('agent', 'Agent'), ('info_officer', 'Information Officer'), ('cashier', 'Cashier')], default='client', max_length=20),
            preserve_default=False,
        ),
    ]
