# Generated by Django 5.1.2 on 2025-03-23 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_type_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +63 XXX-XXX-XXXX', regex='^\\+63 \\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
