# Generated by Django 5.1.5 on 2025-03-02 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Olac', max_length=50, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='Olac', max_length=10, verbose_name='Middle Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=639677902940, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +63 XXX-XXX-XXXX', regex='^\\+63 \\d{3}-\\d{3}-\\d{4}$')]),
            preserve_default=False,
        ),
    ]
