# Generated by Django 5.1.2 on 2025-03-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address_user_middle_name_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
