# Generated by Django 5.1.2 on 2024-12-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='commission_amount',
            new_name='commision_rate',
        ),
    ]
