# Generated by Django 5.1.2 on 2024-12-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_commission_amount_agent_commision_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50, unique=True)),
                ('block_description', models.TextField(blank=True, null=True)),
                ('coordinates', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['block', 'row', 'column']},
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plot',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.block'),
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('row', 'column', 'block')},
        ),
    ]
