# Generated by Django 5.1.2 on 2024-12-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_block_alter_plot_options_alter_plot_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='block',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='price',
        ),
        migrations.AlterField(
            model_name='block',
            name='block_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_type', models.CharField(choices=[('stone', 'Stone Type'), ('lawn', 'Lawn Type'), ('valor', 'Valor Type'), ('mausoleum', 'Mausoleum')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.block')),
            ],
            options={
                'unique_together': {('block', 'plot_type')},
            },
        ),
    ]
