# Generated by Django 5.1.2 on 2024-12-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_block_description_block_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('plot_type',)},
        ),
        migrations.RemoveField(
            model_name='price',
            name='block',
        ),
    ]
