# Generated by Django 5.1.2 on 2025-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('information', 'Information Officer'), ('cashier', 'Cashier'), ('agent', 'Agent'), ('client', 'Client')], max_length=20, null=True),
        ),
    ]
