# Generated by Django 5.1.2 on 2024-12-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_price_unique_together_remove_price_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
