# Generated by Django 5.1.2 on 2025-04-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdetails',
            name='total_sales',
        ),
    ]
