# Generated by Django 5.1.2 on 2024-12-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_block_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
