# Generated by Django 5.1.2 on 2025-04-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_agentdetails_total_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='balance_to_pay',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.profile'),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
