# Generated by Django 5.1.2 on 2025-04-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_clientdetails_balance_to_pay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('reserved', 'Reserved')], default='vacant', max_length=10)),
                ('plot_type', models.CharField(choices=[('stone', 'Stone Type'), ('lawn', 'Lawn Type'), ('valor', 'Valor Type'), ('mausoleum', 'Mausoleum')], max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('max_bodies', models.PositiveIntegerField(default=2)),
                ('plot_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.block')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='core.clientdetails')),
            ],
            options={
                'ordering': ['block', 'plot_id'],
                'unique_together': {('plot_id', 'block')},
            },
        ),
    ]
