# Generated by Django 5.1.2 on 2024-12-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plot_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['block', 'plot_id']},
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('plot_id', 'block')},
        ),
        migrations.RemoveField(
            model_name='plot',
            name='column',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='row',
        ),
    ]
