# Generated by Django 5.1.2 on 2025-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_block_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('vacant', 'Vacant'), ('reserved', 'Reserved')], default='vacant', max_length=10),
        ),
    ]
