# Generated by Django 5.1.2 on 2025-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_plot_options_alter_plot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='max_bodies',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
