# Generated by Django 5.1.2 on 2025-01-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plot_max_bodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='max_bodies',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
