# Generated by Django 5.1.2 on 2025-04-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_plot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='owner',
            new_name='client',
        ),
    ]
