# Generated by Django 5.1.2 on 2025-04-16 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_owner_plot_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='reserved', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, choices=[('money_not_matching', 'Money Not Matching'), ('expired_request', 'Expired Request'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plot')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
            },
        ),
    ]
