# Generated by Django 5.1.2 on 2025-01-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_plot_max_bodies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='name',
            new_name='plot_name',
        ),
        migrations.AddField(
            model_name='plot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
