# Generated by Django 5.1.2 on 2025-01-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_name_plot_plot_name_plot_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_name',
            field=models.CharField(default='BA-P0', max_length=255),
        ),
    ]
