# Generated by Django 5.1.2 on 2025-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='declared_amount',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_plan',
            field=models.CharField(choices=[('12', '12 months'), ('24', '24 months'), ('36', '36 months'), ('full', 'Full payment')], default='full', max_length=4),
        ),
    ]
