# Generated by Django 5.1.2 on 2025-01-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_plot_plot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_name',
            field=models.CharField(max_length=255),
        ),
    ]
