# Generated by Django 5.1.2 on 2025-04-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_paymentrequest_declared_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='core.clientdetails'),
        ),
    ]
