# Generated by Django 5.1.2 on 2025-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_plot_plot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
    ]
