# Generated by Django 5.1.2 on 2025-02-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_block_block_name_alter_block_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
