# Generated by Django 5.1.2 on 2025-04-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_paymentrequest_price_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payments_made', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientdetails')),
                ('last_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plot')),
            ],
            options={
                'unique_together': {('client', 'plot')},
            },
        ),
    ]
