# Generated by Django 5.1.2 on 2025-04-18 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_balancetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetracker',
            name='paymentrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_trackers', to='core.paymentrequest'),
        ),
    ]
