# Generated by Django 5.1.2 on 2025-03-23 09:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_block_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='client',
            name='client_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
