# Generated by Django 5.1.2 on 2025-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_balancetracker_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetracker',
            name='last_amount_paid',
        ),
        migrations.AddField(
            model_name='balancetracker',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
