# Generated by Django 5.1.2 on 2025-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_balancetracker_last_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetracker',
            name='last_payment',
        ),
        migrations.AddField(
            model_name='balancetracker',
            name='last_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
